parameters:
  - name: environmentName
    displayName: Environment name
    type: string
    default: dev

pool:
  vmImage: ubuntu-latest

trigger:
  branches:
    include:
      - master
      - azure-devops-pipelines

variables:
  - group: infrastructure-config
  - name: ADMIN_APP_LOCATION
    value: $(Build.SourcesDirectory)/src/eShopOnTelegram.Admin
  - name: ADMIN_APP_PROJECT_NAME
    value: eShopOnTelegram.Admin
  - name: SHOP_APP_LOCATION
    value: $(Build.SourcesDirectory)/src/eShopOnTelegram.Shop
  - name: SHOP_APP_PROJECT_NAME
    value: eShopOnTelegram.Shop
  - name: DOTNET_VERSION
    value: 7.x
  - name: NODE_VERSION
    value: 18.x

stages:
  - stage: TerraformPlanAndApply${{parameters.environmentName}}
    displayName: Deploy azure infrastructure
    jobs:
      - template: ./templates/terraform-plan-and-apply.yml
        parameters: 
          Environment: ${{parameters.environmentName}}
          PipelineEnvironment: eshopontelegram-${{lower(parameters.environmentName)}}
          TfVarFile: "$(Build.SourcesDirectory)/infrastructure/terraform/vars/${{lower(parameters.environmentName)}}.tfvars"
          TfBackendStateFile: terraform-state-${{lower(parameters.environmentName)}}.tfstate
          SubscriptionId: $(azure-subscription-id)
          TfBackendResourceGroup:  $(terraform-backend-resource-group-name)
          TfBackendStorageAccountName: $(terraform-backend-storage-account-name)
          TfBackendContainerName: $(terraform-backend-blob-container-name)
          TfBackendAccessKey: $(terraform-backend-access-key)
          TfWorkingDirectory: $(Build.SourcesDirectory)/infrastructure/terraform
          TfOutputVars:
            - "resource_group_name"
            - "resource_group_location"
            - "admin_app_name"
            - "admin_app_hostname"
            - "shop_app_name"
            - "key_vault_uri"
          
  - stage: BuildAndDeployAdmin${{parameters.environmentName}}
    dependsOn: ['TerraformPlanAndApply${{parameters.environmentName}}']
    displayName: Build and deploy admin app
    jobs:
      - template: ./templates/dotnet-and-pnpm-client-build-and-deploy.yml
        parameters:
          webAppName: $[stageDependencies.TerraformPlanAndApply${{parameters.environmentName}}.terraform_apply.outputs['terraform_apply.tf_var_admin_app_name.admin_app_name']]
          webAppResourceGroup: $[stageDependencies.TerraformPlanAndApply${{parameters.environmentName}}.terraform_apply.outputs['terraform_apply.tf_var_resource_group_name.resource_group_name']]
          dotnetVersion: ${{ variables.DOTNET_VERSION }}
          nodeVersion: ${{ variables.NODE_VERSION }}
          clientAppPath: ${{ variables.SHOP_APP_LOCATION }}/ClientApp
          dotnetProjectPath: ${{ variables.SHOP_APP_LOCATION }}
          dotnetProjectName: ${{ variables.ADMIN_APP_PROJECT_NAME }}

  - stage: BuildAndDeployShop${{parameters.environmentName}}
    dependsOn: ['TerraformPlanAndApply${{parameters.environmentName}}']
    displayName: Build and deploy admin app
    jobs:
      - template: ./templates/dotnet-and-pnpm-client-build-and-deploy.yml
        parameters:
          webAppName: $[stageDependencies.TerraformPlanAndApply${{parameters.environmentName}}.terraform_apply.outputs['terraform_apply.tf_var_shop_app_name.shop_app_name']]
          webAppResourceGroup: $[stageDependencies.TerraformPlanAndApply${{parameters.environmentName}}.terraform_apply.outputs['terraform_apply.tf_var_resource_group_name.resource_group_name']]
          dotnetVersion: ${{ variables.DOTNET_VERSION }}
          nodeVersion: ${{ variables.NODE_VERSION }}
          clientAppPath: ${{ variables.SHOP_APP_LOCATION }}/WebApp
          dotnetProjectPath: ${{ variables.SHOP_APP_LOCATION }}
          dotnetProjectName: ${{ variables.SHOP_APP_PROJECT_NAME }}