parameters:
  - name: webAppName
  - name: webAppResourceGroup
  - name: dotnetVersion
  - name: nodeVersion
  - name: clientAppPath
  - name: dotnetProjectPath
  - name: azureSubscription
    default: $(azure-subscription-id)
  - name: publishOutputPath
    default: ''

jobs:
  - job: build_and_deploy
    displayName: Build and deploy app
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET ${{parameters.dotnetVersion}} SDK'
      inputs:
        version: ${{parameters.dotnetVersion}}
        performMultiLevelLookup: true

    - task: NodeTool@0
      displayName: 'Use NodeJS version ${{parameters.nodeVersion}}'
      inputs:
        versionSpec: ${{parameters.nodeVersion}}

    - script: npm install -g pnpm
      displayName: 'Install pnpm'

    - script: pnpm install
      workingDirectory: ${{parameters.clientAppPath}}
      displayName: 'Install node modules'

    - script: pnpm build
      workingDirectory: ${{parameters.clientAppPath}}
      displayName: 'Build client app'

    - script: dotnet publish -c Release --output ${{ parameters.publishOutputPath }}
      workingDirectory: ${{parameters.dotnetProjectPath}}
      displayName: 'Publish dotnet project'

    - task: AzureWebApp@1
      displayName: Deploy app to azure
      inputs:
        azureSubscription: "Azure subscription 1 (349526ee-2859-455b-8a10-1ffc02973465)"
        appType: webAppLinux
        appName: ${{ parameters.webAppName }}
        package: ${{ parameters.publishOutputPath }}
        resourceGroupName: ${{ parameters.webAppResourceGroup }}