parameters:
  - name: webAppName
  - name: webAppResourceGroup
  - name: dotnetVersion
  - name: nodeVersion
  - name: clientAppPath
  - name: dotnetProjectPath
  - name: azureSubscription
    default: $(azure-subscription-id)
  - name: publishOutputPath
    default: ''

jobs:
  - job: build_and_deploy
    displayName: Build and deploy app
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET ${{parameters.dotnetVersion}} SDK'
      inputs:
        version: ${{parameters.dotnetVersion}}
        performMultiLevelLookup: true

    - task: NodeTool@0
      displayName: 'Use NodeJS version ${{parameters.nodeVersion}}'
      inputs:
        versionSpec: ${{parameters.nodeVersion}}

    - script: npm install -g pnpm
      displayName: 'Install pnpm'

    - script: pnpm install
      workingDirectory: ${{parameters.clientAppPath}}
      displayName: 'Install node modules'

    - task: DotNetCoreCLI@2
      displayName: 'Restore projects ${{parameters.dotnetProjectPath}}'
      inputs:
        projects: |
          ${{parameters.dotnetProjectPath}}
        command: 'restore'

    - task: DotNetCoreCLI@2
      displayName: 'Build ${{parameters.dotnetProjectPath}}'
      inputs:
        command: publish
        projects:  ${{parameters.dotnetProjectPath}}
        publishWebProjects: false
        arguments: '--no-restore --configuration Release --output ${{ parameters.publishOutputPath }}'
        zipAfterPublish: true

    - task: AzureWebApp@1
      displayName: Deploy app to azure
      inputs:
        appType: webApp
        azureSubscription: ${{ parameters.azureSubscription }} 
        appName: ${{ parameters.webAppName }}
        package: ${{ parameters.publishOutputPath }}
        resourceGroupName: ${{ parameters.webAppResourceGroup }}