parameters:
- name: Environment 
- name: TfVersion 
  default: 1.3.3 
- name: TfBackendResourceGroup 
- name: TfBackendStorageAccountName 
- name: TfBackendContainerName 
- name: TfBackendAccessKey 
- name: TfBackendStateFile 
- name: TfWorkingDirectory 
- name: TfPlanName
  default: tfplan
- name: SpnClientId 
  default: $(azure-spn-client-id)
- name: SpnClientSecret 
  default: $(azure-spn-client-secret)
- name: SpnTenantId 
  default: $(azure-spn-tenant-id)
- name: SpnObjectId 
  default: $(azure-spn-object-id)
- name: SubscriptionId 
- name: TfVarFile 
- name: PipelineEnvironment
- name: TfOutputVars
  type: object
  default: ''

jobs:
  - job: terraform_plan
    displayName: Terraform plan
    steps:
    - template: terraform-plan-steps.yml  
      parameters:
        Environment: ${{parameters.Environment}}
        TfVersion: ${{parameters.TfVersion}}
        TfBackendResourceGroup: ${{parameters.TfBackendResourceGroup}}
        TfBackendStorageAccountName: ${{parameters.TfBackendStorageAccountName}}
        TfBackendContainerName: ${{parameters.TfBackendContainerName}}
        TfBackendAccessKey: ${{parameters.TfBackendAccessKey}}
        TfBackendStateFile: ${{parameters.TfBackendStateFile}}
        TfWorkingDirectory: ${{parameters.TfWorkingDirectory}}
        TfPlanName: ${{parameters.TfPlanName}}
        SpnClientId: ${{parameters.SpnClientId}}
        SpnClientSecret: ${{parameters.SpnClientSecret}}
        SpnTenantId: ${{parameters.SpnTenantId}}
        SpnObjectId: ${{parameters.SpnObjectId}}
        SubscriptionId: ${{parameters.SubscriptionId}}
        TfVarFile: ${{parameters.TfVarFile}}

  - deployment: terraform_apply
    displayName: Terraform apply
    dependsOn: terraform_plan
    continueOnError: false
    environment: ${{parameters.PipelineEnvironment}}
    timeoutInMinutes: 120
    strategy:
      runOnce:
        deploy: 
          steps:
          - template: terraform-apply-steps.yml
            parameters:
              Environment: ${{parameters.Environment}}
              TfVersion: ${{parameters.TfVersion}}
              TfBackendResourceGroup: ${{parameters.TfBackendResourceGroup}}
              TfBackendStorageAccountName: ${{parameters.TfBackendStorageAccountName}}
              TfBackendContainerName: ${{parameters.TfBackendContainerName}}
              TfBackendAccessKey: ${{parameters.TfBackendAccessKey}}
              TfBackendStateFile: ${{parameters.TfBackendStateFile}}
              TfWorkingDirectory: ${{parameters.TfWorkingDirectory}}
              TfOutputVars: ${{parameters.TfOutputVars}}         