resource_group_name = "rg-eshopontelegram-dev"
app_environment = "Dev"
sql_server_name = "sqlserver-eshopontelegram-dev"
sql_database_name = "db-eshopontelegram-dev"
storage_account_name = "steshopontelegramdev"
app_service_plan_name = "serviceplan-eshopontelegram-dev"
admin_app_name = "app-admin-eshopontelegram-dev"
telegram_webapp_name = "app-telegramwebapp-eshopontelegram-dev"