name: Deploy infrastructure and application

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      environment:
        required: true
        default: 'dev'

env:
  ARM_CLIENT_ID: ${{ secrets.GH_SP_AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.GH_SP_AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ADMIN_APP_LOCATION: src/eShopOnTelegram.Admin
  TELEGRAM_BOT_LOCATION: src/eShopOnTelegram.TelegramBot
  DOTNET_VERSION: 7.x

jobs:
  deploy_infrastructure:
    runs-on: ubuntu-latest
    
    name: Deploy Azure infrastructure
    environment:
      name: ${{ github.event.inputs.environment || 'dev' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Initialize Terraform
        working-directory: terraform
        run: terraform init -backend-config=resource_group_name=rg-infrastructure-administration -backend-config="storage_account_name=stcommonterraformstate" -backend-config="container_name=eshopontelegram-terraform-state" -backend-config="key=terraform-state-${{ github.event.inputs.environment || 'dev' }}.tfstate" -reconfigure

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan -input=false -out=plan -var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" -var="app_sp_object_id=${{ secrets.APP_SP_AZURE_OBJECT_ID }}" -var="app_sp_client_id=${{ secrets.APP_SP_AZURE_CLIENT_ID }}" -var="app_sp_client_secret=${{ secrets.APP_SP_AZURE_CLIENT_SECRET }}" -var="admin_object_id=${{ secrets.ADMIN_AZURE_OBJECT_ID }}" -var="sp_object_id=${{ secrets.GH_SP_AZURE_OBJECT_ID }}" -var="sql_admin_password=${{ secrets.SQL_ADMIN_PASSWORD }}" -var="telegram_bot_owner_telegram_id=${{ secrets.TELEGRAM_BOT_OWNER_TELEGRAM_ID }}" -var="telegram_token=${{ secrets.TELEGRAM_TOKEN }}" -var="payment_card_api_token=${{ secrets.PAYMENT_CARD_API_TOKEN }}" -var="payment_plicio_api_token=${{ secrets.PAYMENT_PLICIO_API_TOKEN }}" -var-file="vars/${{ github.event.inputs.environment || 'dev' }}.tfvars"

      - name: Teffaform Apply
        id: terraformapply
        working-directory: terraform
        run: terraform apply "plan"

      - name: Set terraform output to GitHub env variables
        working-directory: terraform
        id: terraformoutput
        run: |
          echo "resourceGroupName=$(terraform output -raw resource_group_name)" >> $GITHUB_OUTPUT
          echo "resourceGroupLocation=$(terraform output -raw resource_group_location)" >> $GITHUB_OUTPUT
          echo "adminAppName=$(terraform output -raw admin_app_name)" >> $GITHUB_OUTPUT
          echo "adminAppHostName=$(terraform output -raw admin_app_hostname)" >> $GITHUB_OUTPUT
          echo "telegramBotAppName=$(terraform output -raw telegram_bot_app_name)" >> $GITHUB_OUTPUT
          echo "keyVaultUri=$(terraform output -raw key_vault_uri)" >> $GITHUB_OUTPUT
      
    outputs:
      resourceGroupName: ${{ steps.terraformoutput.outputs.resourceGroupName }}
      resourceGroupLocation: ${{ steps.terraformoutput.outputs.resourceGroupLocation }}
      adminAppName: ${{ steps.terraformoutput.outputs.adminAppName }}
      adminAppHostName: ${{ steps.terraformoutput.outputs.adminAppHostName }}
      telegramBotAppName: ${{ steps.terraformoutput.outputs.telegramBotAppName }}
      keyVaultUri: ${{ steps.terraformoutput.outputs.keyVaultUri }}

  deploy_admin_app:
    runs-on: ubuntu-latest
    
    name: Deploy admin app to ${{ github.event.inputs.environment || 'dev' }} env
    needs: [deploy_infrastructure]
    environment:
      name: ${{ github.event.inputs.environment || 'dev' }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Restore NuGet packages
        working-directory: ${{ env.ADMIN_APP_LOCATION }}
        run: dotnet restore

      - name: Build admin application
        working-directory: ${{ env.ADMIN_APP_LOCATION }}
        run: dotnet build --configuration Release --no-restore
      
      - name: Publish admin application
        working-directory: ${{ env.ADMIN_APP_LOCATION }}
        run: dotnet publish --configuration Release --no-build --output publish

      - name: Azure CLI Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.GH_SP_AZURE_CREDENTIALS }}

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ needs.deploy_infrastructure.outputs.adminAppName }}
          package: ${{ env.ADMIN_APP_LOCATION }}/publish

  deploy_telegram_webapp:
    runs-on: ubuntu-latest
    
    name: 'Deploy telegram webapp'
    needs: [deploy_infrastructure]
    environment:
      name: ${{ github.event.inputs.environment || 'dev' }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Restore NuGet packages
        working-directory: ${{ env.TELEGRAM_BOT_LOCATION }}
        run: dotnet restore

      - name: Build telegram bot project
        working-directory: ${{ env.TELEGRAM_BOT_LOCATION }}
        run: dotnet build --configuration Release --no-restore
      
      - name: Publish telegram bot project
        working-directory: ${{ env.TELEGRAM_BOT_LOCATION }}
        run: dotnet publish --configuration Release --no-build --output publish

      - name: Azure CLI Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.GH_SP_AZURE_CREDENTIALS }}

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ needs.deploy_infrastructure.outputs.telegramBotAppName }}
          package: ${{ env.TELEGRAM_BOT_LOCATION }}/publish
